name: Plugination
version: 1.0
main: com.amazingthings.plugination.Plugination
description: Plug the Nation ._.
 
commands:
    bacon:
        description: BAAAACON.
    test:
        description: Do stuff.
    removebacon:
        description: Remove BAAAACON :3.