name: Plugination
version: 1.0
main: com.amazingthings.plugination.Plugination
description: Plug the Nation ._.
 
commands:
    creload:
        usage: /<command>
        description: Reloads all configuration and data files.
    test:
        usage: /<command>
        description: Do stuff.